#get the latest alpine image from node registry
FROM node:18-alpine AS dependencies
# RUN npm i -g yarn
#set the working directory
WORKDIR /app

#copy the package and package lock files
#from local to container work directory /app
COPY package.json /app/

#Run command npm install to install packages
RUN yarn

#copy all the folder contents from local to container & build
FROM node:18-alpine as builder

ARG NEXT_PUBLIC_SOCKET_URL
ARG NEXT_PUBLIC_BOT_ID
ARG NEXT_PUBLIC_TELEMETRY_API
ARG NEXT_PUBLIC_AI_TOOLS_API
ARG NEXT_PUBLIC_BFF_API_URL
ARG NEXT_PUBLIC_USER_SERVICE_APP_ID
ARG NEXT_PUBLIC_JWKS_URI
ARG NEXT_PUBLIC_USER_SERVICE_URL
ARG NEXT_PUBLIC_ORG_ID
ARG NEXT_PUBLIC_CONFIG_BASE_URL
ARG NEXT_PUBLIC_BOT_NAME
ARG NEXT_PUBLIC_ENTITY_DATASET_ID
ARG NEXT_PUBLIC_DEBUG
ARG NEXT_PUBLIC_SOCKET_PATH
ARG NEXT_PUBLIC_GOOGLE_KEY
ARG FUSIONAUTH_URL
ARG FUSIONAUTH_KEY
ARG NEXT_PUBLIC_DATASET_URL
ARG NEXT_PUBLIC_CLARITY_PROJECT_ID
ARG NEXT_PUBLIC_SHOW_ONBOARDING
ARG NEXT_PUBLIC_WEATHER_API

ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_BOT_ID=$NEXT_PUBLIC_BOT_ID
ENV NEXT_PUBLIC_TELEMETRY_API=$NEXT_PUBLIC_TELEMETRY_API
ENV NEXT_PUBLIC_AI_TOOLS_API=$NEXT_PUBLIC_AI_TOOLS_API
ENV NEXT_PUBLIC_BFF_API_URL=$NEXT_PUBLIC_BFF_API_URL
ENV NEXT_PUBLIC_USER_SERVICE_APP_ID=$NEXT_PUBLIC_USER_SERVICE_APP_ID
ENV NEXT_PUBLIC_JWKS_URI=$NEXT_PUBLIC_JWKS_URI
ENV NEXT_PUBLIC_USER_SERVICE_URL=$NEXT_PUBLIC_USER_SERVICE_URL
ENV NEXT_PUBLIC_ORG_ID=$NEXT_PUBLIC_ORG_ID
ENV NEXT_PUBLIC_CONFIG_BASE_URL=$NEXT_PUBLIC_CONFIG_BASE_URL
ENV NEXT_PUBLIC_BOT_NAME=$NEXT_PUBLIC_BOT_NAME
ENV NEXT_PUBLIC_ENTITY_DATASET_ID=$NEXT_PUBLIC_ENTITY_DATASET_ID
ENV NEXT_PUBLIC_DEBUG=$NEXT_PUBLIC_DEBUG
ENV NEXT_PUBLIC_SOCKET_PATH=$NEXT_PUBLIC_SOCKET_PATH
ENV NEXT_PUBLIC_GOOGLE_KEY=$NEXT_PUBLIC_GOOGLE_KEY
ENV FUSIONAUTH_URL=$FUSIONAUTH_URL
ENV FUSIONAUTH_KEY=$FUSIONAUTH_KEY
ENV NEXT_PUBLIC_DATASET_URL=$NEXT_PUBLIC_DATASET_URL
ENV NEXT_PUBLIC_CLARITY_PROJECT_ID=$NEXT_PUBLIC_CLARITY_PROJECT_ID
ENV NEXT_PUBLIC_SHOW_ONBOARDING=$NEXT_PUBLIC_SHOW_ONBOARDING
ENV NEXT_PUBLIC_WEATHER_API=$NEXT_PUBLIC_WEATHER_API


WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN yarn run build

#specify env variables at runtime
FROM node:18-alpine as runner
WORKDIR /app

# If you are using a custom next.config.js file, uncomment this line.
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["yarn", "start"]