module.exports = [
  {
    componentName: "Bot Details",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "component",
    props: {
      keyName: "botDetails",
      children: [
        {
          componentType: "textInput",
          componentName: "Bot Name",
          keyName: "botName",
          defaultValue: "botName",
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "botLogo",
          keyName: "logo",
          defaultValue: "",
          allowOverride: true,
        }
      ],
    },
  },
  {
    componentName: 'Primary Main Color',
    componentType: 'colorpicker',
    defaultValue: '#ffffff',
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: 'primary',
    props: {
      keyName: 'main',
      children: [],
    },
  },
  {
    componentName: 'Primary Light Color',
    componentType: 'colorpicker',
    defaultValue: '#ffffff',
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: 'primary',
    props: {
      keyName: 'light',
      children: [],
    },
  },
  {
    componentName: 'Primary Dark Color',
    componentType: 'colorpicker',
    defaultValue: '#ffffff',
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: 'primary',
    props: {
      keyName: 'dark',
      children: [],
    },
  },
  {
    componentName: 'Primary Contrast Text Color',
    componentType: 'colorpicker',
    defaultValue: '#ffffff',
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: 'primary',
    props: {
      keyName: 'contrastText',
      children: [],
    },
  },
  {
    componentName: "Home Page",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "component",
    props: {
      keyName: "homePage",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showHomePage",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Home Page Title",
          keyName: "title",
          defaultValue: "Ask me anything about farming",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Show Kalia Status Button",
          keyName: "showKalia",
          defaultValue: false,
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "Kalia Status Logo",
          keyName: "kaliaStatusImg",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Show Weather Advisory Button",
          keyName: "showWeatherAdvisory",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "Weather Advisory Logo",
          keyName: "weatherAdvisoryImg",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Show Plant Protection Button",
          keyName: "showPlantProtection",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "Plant Protection Logo",
          keyName: "plantProtectionImg",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Show Mic",
          keyName: "showMic",
          defaultValue: true,
          allowOverride: true,
        },
      ]
    }
  },
  {
    componentName: "Navbar",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "component",
    props: {
      keyName: "navbar",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showNavbar",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Brand Name",
          keyName: "brandName",
          defaultValue: "brandName",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Show Hamburger Menu",
          keyName: "showHamburgerMenu",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Show Home Icon",
          keyName: "showHomeIcon",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "Right Side Logo",
          keyName: "rightLogo",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "Left Side Logo",
          keyName: "leftLogo",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "Center Side Logo",
          keyName: "centerLogo",
          defaultValue: "",
          allowOverride: true,
        },
      ],
    },
  },
  {
    componentName: "Down Time Page",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "downtimePage",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showDowntimePage",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Title",
          keyName: "title",
          defaultValue: "We're under maintainance",
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "Downtime Image",
          keyName: "downTimeImage",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Supporting Text",
          keyName: "supportingText",
          defaultValue: "Have an urgent query?",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Contact Link Text",
          keyName: "contactLink",
          defaultValue: "Call Us",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Refresh Text",
          keyName: "refreshText",
          defaultValue: "Try Again",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Previous Page Text",
          keyName: "previousPageText",
          defaultValue: "Previous Page",
          allowOverride: true,
        },
      ],
    },
  },
  {
    componentName: "Coming Soon Page",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "comingSoonPage",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showComingSoonPage",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Title",
          keyName: "title",
          defaultValue: "Coming Soon!",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Description",
          keyName: "description",
          defaultValue:
            "We are going to launch this feature very soon. Stay tuned!",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Back Button Text",
          keyName: "backText",
          defaultValue: "Back",
          allowOverride: true,
        },
      ],
    },
  },
  {
    componentName: "FAQs Page",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "faqs",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showFAQsPage",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Title",
          keyName: "title",
          defaultValue: "faqs",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "User Manual Text",
          keyName: "userManualText",
          defaultValue: "User Manual - For VAWs",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Contact Description Text",
          keyName: "contactDescriptionText",
          defaultValue: "To connect with call centre",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Contact Text",
          keyName: "contactText",
          defaultValue: "Dial 155333",
          allowOverride: true,
        },
      ],
    },
  },
  {
    componentName: "Sidebar",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "component",
    props: {
      keyName: "sidebar",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showSidebar",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: " Show Language Switcher",
          keyName: "languageSwitcher",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Language  1 Code  ",
          keyName: "languageCode1",
          defaultValue: "en",
          allowOverride: true,
        },

        {
          componentType: "textInput",
          componentName: "Language 1 Label ",
          keyName: "languageName1",
          defaultValue: "English",
          allowOverride: true,
        },

        {
          componentType: "textInput",
          componentName: "Language 2 Code",
          keyName: "languageCode2",
          defaultValue: "en",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Language 2 Label",
          keyName: "languageName2",
          defaultValue: "notEnglish",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: " Show Profile Icon",
          keyName: "profilePicture",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Profile Text ",
          keyName: "languageName",
          defaultValue: "Welcome User",
          allowOverride: true,
        },

        {
          componentType: "booleanInput",
          componentName: " Show FAQ Page",
          keyName: "faqPage",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: " FAQ Page Label ",
          keyName: "faqPageLabel",
          defaultValue: "FAQs",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: " Show Chat History Page",
          keyName: "historyPage",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Chat History Page Label ",
          keyName: "chatsPageLabel",
          defaultValue: "Chats",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: " Show Feedback Page",
          keyName: "feedbackPage",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Feedback Page Label",
          keyName: "feedbackPageLabel",
          defaultValue: "Feedback",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: " Show Logout Button",
          keyName: "profilePicture",
          defaultValue: "",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Logout Button Label",
          keyName: "logoutButton",
          defaultValue: "Logout",
          allowOverride: true,
        },
      ],
    },
  },
  {
    componentName: 'ChatUI',
    componentType: 'component',
    defaultValue: '',
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: 'molecule',
    props: {
      keyName: 'chatUI',
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showChatUI",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: 'textInput',
          componentName: 'Placeholder Text',
          keyName: 'placeholder',
          defaultValue: 'Ask Your Question',
          allowOverride: true,
        },
        {
          componentType: 'booleanInput',
          componentName: 'Allow Feedback',
          keyName: 'allowFeedback',
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: 'textInput',
          componentName: 'Positive Feedback Text',
          keyName: 'positiveFeedbackText',
          defaultValue: 'Helpful',
          allowOverride: true,
        },
        {
          componentType: 'textInput',
          componentName: 'Negative Feedback Text',
          keyName: 'negativeFeedbackText',
          defaultValue: 'Not Helpful',
          allowOverride: true,
        },
        {
          componentType: 'booleanInput',
          componentName: 'Allow Text to Speech',
          keyName: 'allowTextToSpeech',
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: 'textInput',
          componentName: 'Text to Speech Label',
          keyName: 'textToSpeechLabel',
          defaultValue: 'Click to hear',
          allowOverride: true,
        },
        {
          componentType: 'booleanInput',
          componentName: 'Show Transliteration',
          keyName: 'allowTransliteration',
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: 'textInput',
          componentName: 'Transliteration API',
          keyName: 'transliterationApi',
          defaultValue: 'https://ai-tools-proxy.staging.bhasai.samagra.io',
          allowOverride: true,
        },
        {
          componentType: 'textInput',
          componentName: 'Transliteration Input Language',
          keyName: 'transliterationInputLanguage',
          defaultValue: 'en',
          allowOverride: true,
        },
        {
          componentType: 'textInput',
          componentName: 'Transliteration Output Language',
          keyName: 'transliterationOutputLanguage',
          defaultValue: 'or',
          allowOverride: true,
        },
        {
          componentType: 'textInput',
          componentName: 'Transliteration Provider',
          keyName: 'transliterationProvider',
          defaultValue: 'bhashini',
          allowOverride: true,
        },
        {
          componentType: 'numberInput',
          componentName: 'Transliteration Number of Suggestions',
          keyName: 'transliterationSuggestions',
          defaultValue: 3,
          allowOverride: true,
        }
       ]
    }
  },
  {
    componentName: "Feedback Page",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "feedbackPage",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showFeedbackPage",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Title",
          keyName: "Title",
          defaultValue: "Feedback",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Rating Box Availability",
          keyName: "ratingBox",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "numberInput",
          componentName: "Max Stars",
          keyName: "ratingMaxStars",
          defaultValue: 5,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Rating Box Title",
          keyName: "ratingBoxTitle",
          defaultValue: "Did you find this useful?",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Rating Description",
          keyName: "ratingStarDescription",
          defaultValue: "Tap a star to rate",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Submit Review Button",
          keyName: "ratingButtonText",
          defaultValue: "Submit Review",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Review Box Availability",
          keyName: "reviewBox",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Review Box Title",
          keyName: "reviewBoxTitle",
          defaultValue: "Write your review (optional)",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Submit Review Button",
          keyName: "reviewButtonText",
          defaultValue: "Submit Review",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Review Box Placeholder value",
          keyName: "reviewPlaceholder",
          defaultValue: "Give positive/negative feedback for advisory",
          allowOverride: true,
        },
      ],
    },
  },
  {
    componentName: "Voice Recorder",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "voiceRecorder",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showVoiceRecorder",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "numberInput",
          componentName: "Delay between dialogs",
          keyName: "delayBetweenDialogs",
          defaultValue: 2500,
          allowOverride: true,
        },
      ],
    },
  },
  {
    componentName: "Launch Page",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "launchPage",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showLaunchPage",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Title",
          keyName: "label",
          defaultValue: "Launch Label",
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "Launch Icon",
          keyName: "icon",
          defaultValue: "",
          allowOverride: true,
        },
      ],
    },
  },
  {
    componentName: "Otp Page",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "otpPage",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showOtpPage",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Title",
          keyName: "title",
          defaultValue: "OTP Verification",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Resend Otp Timer",
          keyName: "resendOtpTimer",
          defaultValue: "30",
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "OTP length",
          keyName: "otpLength",
          defaultValue: "4",
          allowOverride: true,
        },
        {
          componentType: "fileInput",
          componentName: "Logo",
          keyName: "logo",
          defaultValue: "",
          allowOverride: true,
        },{
          componentType: "booleanInput",
          componentName: "Show Splited View",
          keyName: "showSplitedView",
          defaultValue: "true",
          allowOverride: true,
        },{
          componentType: "booleanInput",
          componentName: "Show logo",
          keyName: "showLogo",
          defaultValue: "false",
          allowOverride: true,
        },
      ],
    },
  },
  {
    componentName: "Login Page",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "loginMobileAadharPage",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Show Component",
          keyName: "showLoginMobileAadharPage",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Title",
          keyName: "title",
          defaultValue: "Welcome!",
          allowOverride: true,
        },{
          componentType: "fileInput",
          componentName: "Logo",
          keyName: "logo",
          defaultValue: "",
          allowOverride: true,
        },{
          componentType: "booleanInput",
          componentName: "Show Splited View",
          keyName: "showSplitedView",
          defaultValue: "true",
          allowOverride: true,
        },{
          componentType: "booleanInput",
          componentName: "Show Logo",
          keyName: "showLogo",
          defaultValue: "false",
          allowOverride: true,
        },{
          componentType: "booleanInput",
          componentName: "Show Alternate SignIn",
          keyName: "showAlternateSignIn",
          defaultValue: "false",
          allowOverride: true,
        },{
          componentType: "booleanInput",
          componentName: "Show Sign Up",
          keyName: "showSignUp",
          defaultValue: "false",
          allowOverride: true,
        },{
          componentType: "booleanInput",
          componentName: "Login With Aadhaar",
          keyName: "loginWithAadhaar",
          defaultValue: "false",
          allowOverride: true,
        },
      ],
    },
  },

  {
    componentName: "History",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "historyPage",
      children: [
        {
          componentType: "textInput",
          componentName: "Title",
          keyName: "title",
          defaultValue: "Chats",
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Delete chat feature",
          keyName: "allowDelete",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Allow to show timestamp",
          keyName: "showTimestamp",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "textInput",
          componentName: "Empty chat history",
          keyName: "noItemsText",
          defaultValue: "No items found",
          allowOverride: true,
        }
      ],
    },
  },

  {
    componentName: "Share and Download buttons",
    componentType: "component",
    defaultValue: "",
    allowOverride: true,
    isAvailable: true,
    showInAdmin: true,
    category: "molecule",
    props: {
      keyName: "share-buttons",
      children: [
        {
          componentType: "booleanInput",
          componentName: "Download chat feature",
          keyName: "allowDownloadChat",
          defaultValue: true,
          allowOverride: true,
        },
        {
          componentType: "booleanInput",
          componentName: "Share chat feature",
          keyName: "allowShareChat",
          defaultValue: true,
          allowOverride: true,
        }
      ],
    },
  }

];
