import DowntimePage from './downtime-page';
import FAQPage from './faq-page';
import FeedbackPage from './feedback';
import HistoryPage from './history-page';
import HomePage from './home-page';
import LocalHomePage from './localize-home-page';
import LaunchPage from './launch-page';
import LoginMobileAadharPage from './login-mobile-aadhar-page';
import OtpPage from './otp-page';
import LocalOtpPage from './localize-otp-page';
import ComingSoonPage from './coming-soon-page';
import LocalLaunchPage from './localize-launch-page';
import LocalLoginMobileAadharPage from './localize-login-mobile-aadhar-page';
import OnBoardingPage from './on-boarding-page';
import WheatherPage from './weather-page';
export { ComingSoonPage, DowntimePage, FeedbackPage, HomePage, LaunchPage, LoginMobileAadharPage, OtpPage, FAQPage, LocalHomePage, LocalLaunchPage, LocalOtpPage, LocalLoginMobileAadharPage, HistoryPage, OnBoardingPage, WheatherPage };